# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='post',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
