# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-15 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='text',
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='/image', width_field='width'),
        ),
    ]
