# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-15 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170615_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='map',
            name='image',
        ),
    ]
